### ISSUE TITLE
Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' .Net Core 3.0

### ISSUE THREAD

**Issue by blogcraft** [KissLog-net/KissLog.Sdk#15] opened 2019-09-25 14:41 UTC
Using Net Core 3.0 There is a new error with kisslog 2.4.0

```
System.TypeLoadException: Could not load type 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' from assembly 'Microsoft.AspNetCore.Http, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at KissLog.AspNetCore.WebRequestPropertiesFactory.ReadInputStream(HttpRequest request)
   at KissLog.AspNetCore.WebRequestPropertiesFactory.Create(HttpRequest request)
   at KissLog.AspNetCore.KissLogMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by catalingavan** [comment] 2019-09-25 14:54
Hi @blogcraft,

I will investigate the issue, and I will come back with further details.
If possible, can you provide some details, please:

1. The error happened after updating the `KissLog.AspNetCore` NuGet package on an existing application?

2. Have you updated the application from targeting .NET Core 2.0 to .NET Core 3.0?

3. Is this a brand new .NET Core 3.0 application, on which you are trying to install `KissLog.AspNetCore` NuGet

The error is related to 'Microsoft.AspNetCore.Http.Internal.BufferingHelper' type, which might not be  available on .NET Core 3.0 anymore.

**Comment by blogcraft** [comment] 2019-09-25 15:45
Hi, thanks for the quick response.

The app Was originally working fine targeting .Net Core 2.2 and KissLog.AspNetCore "1.7.0"

After updating the App to .Net Core 3.0 the app started to fail.
Then I updated KissLog.AspNetCore to 2.4.0 to see if it could solve it, but didn't.

**Comment by catalingavan** [comment] 2019-09-25 15:46
Thanks.
I will replicate the scenario on an .NET Core 3.0 app

**Comment by catalingavan** [comment] 2019-09-25 16:51
Hi @blogcraft,

The issue is caused, indeed, by some incompatibility between `KissLog.AspNetCore` and .NET Core 3.0.
I will create a package update with a fix, but this might take some time.

(More details about this can be found here: https://github.com/aspnet/AspNetCore/issues/12505)

Meanwhile, I suggest a small workaround, just to keep the project running.

KissLog won't log the `Request.InputStream` value anymore, but it will not raise an exception.

Update **Startup.cs** ConfigureServices()
```
public class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public IConfiguration Configuration { get; }

    public void ConfigureServices(IServiceCollection services)
    {
        #region Temporary fix for KissLog .NET Core 3.0 issue
		
        Type type = typeof(KissLog.Internal.InternalHelpers);
        var field = type.GetField("InputStreamContentTypes", BindingFlags.Public | BindingFlags.Static);
        field.SetValue(null, new string[] { });
		
        #endregion
		
        services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();
        services.AddScoped<ILogger>((context) =>
		{
            return Logger.Factory.Get();
        });

        services.AddControllersWithViews();
    }
}
```

Please let me know if this worked for you.

**Comment by blogcraft** [comment] 2019-09-25 17:06
Thanks a lot, the workaround did help!

Looking forward to package update fix when it's available.

**Comment by catalingavan** [comment] 2019-09-26 13:42
Hi @blogcraft 

The issue should be fixed now.

Please update the package to KissLog.AspNetCore 2.4.2

Let me know if everything is working properly.

Thanks

**Comment by blogcraft** [comment] 2019-09-26 14:43
Flawless! It works like a charm! Thanks

**Closed** 2019-09-26 14:47 UTC
Labels: AspNetCore
